apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: mehulnved/nginx:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:0.8.0
        args:
        - '-nginx.scrape-uri'
        - 'http://nginx/metrics'
        imagePullPolicy: Always
        ports:
        - containerPort: 9113
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    name: nodejs
spec:
  selector:
    matchLabels:
      name: nodejs
  template:
    metadata:
      labels:
        name: nodejs
    spec:
      containers:
      - name: nodejs
        image: mehulnved/node:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
