apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
spec:
  type: ClusterIP
  ports:
  - name: http-nginx
    port: 80
  selector:
    name: nginx
